# Generated by Django 4.0.6 on 2022-08-08 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddClass',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('class_title', models.CharField(max_length=30)),
                ('total_seat', models.IntegerField()),
                ('available_seat', models.IntegerField()),
            ],
        ),
    ]
